# Steady State Probabilites
If each column has the same value, it's in a steady state

In [3]:
import numpy as np
from numpy.linalg import matrix_power
from numpy.linalg import linalg, inv

P = np.array([ [0.033, 0.267, 0.6, 0.1], 
               [0.329, 0.013, 0.132, 0.526],
               [0.2, 0.267, 0.133, 0.4],
               [0.1, 0.6, 0.2, 0.1]])

n = 1000 # raise the matrix to a LARGE power n for steady-state
Q = matrix_power(P,n)
SS = Q[0]
print(f"{Q}")
print("\n")

print(f"Steady state probabilities:\n\n{SS}") # This will just print one row

[[0.17830961 0.29119421 0.23572881 0.29476737]
 [0.17830961 0.29119421 0.23572881 0.29476737]
 [0.17830961 0.29119421 0.23572881 0.29476737]
 [0.17830961 0.29119421 0.23572881 0.29476737]]


Steady state probabilities:

[0.17830961 0.29119421 0.23572881 0.29476737]
