# CTMC Mean First Passage Time Standalone Function

In [1]:
import numpy as np

def CTMC_MFPT(infinitesimal_generator, initial_state, destination_state):
    # Remove the destination state row and column from the infinitesimal generator to create A
    A = np.delete(np.delete(infinitesimal_generator, destination_state, axis=0), destination_state, axis=1)
    print(A)
    
    # Create b as a vector of -1's with the same length as A
    b = -np.ones(len(A))

    # Solve the system of linear equations
    X = np.linalg.solve(A, b)
    
    # If initial state is greater than destination state, reverse the order of X
    if initial_state > destination_state:
        X = np.roll(X, destination_state)
        
    return X

# infinitesimal_generator = np.array([[-4, 4, 0],
#                                     [3, -5, 2],
#                                     [0, 1, -1]])

# infinitesimal_generator = np.array([[-3, 1, 2, 0],
#                                     [3, -4, 0.5, 0.5],
#                                     [0, 1, -1.5, 0.5],
#                                     [1, 0, 0, -1]])

infinitesimal_generator = np.array([[-4, 2, 1, 1],
                                    [1, -4, 1, 2],
                                    [1, 2, -4, 1],
                                    [3, 2, 1, -6]])

# infinitesimal_generator = np.array([[-8, 6, 2],
#                                     [2, -6, 4],
#                                     [1, 3, -4]])

# infinitesimal_generator = np.array([[-5/6, 1/3, 1/2, 0],
#                                     [0, -1/3, 0, 1/3],
#                                     [0, 0, -1/2, 1/2],
#                                     [1/6, 0, 0, -1/6]])

# infinitesimal_generator = np.array([[-3, 1, 2],
#                                    [3, -3.5, 0.5],
#                                    [0, 1, -1]])


initial_state = 1
destination_state = 4

if initial_state > destination_state:
    MFPT = CTMC_MFPT(infinitesimal_generator, initial_state, destination_state-1)
    print("Mean First Passage Time from state {} to state {}: {}".format(initial_state, destination_state, MFPT[initial_state-2]))
    print(MFPT)
else:
    MFPT = CTMC_MFPT(infinitesimal_generator, initial_state, destination_state-1)
    print("Mean First Passage Time from state {} to state {}: {}".format(initial_state, destination_state, MFPT[initial_state-1]))
    print(MFPT)


[[-4  2  1]
 [ 1 -4  1]
 [ 1  2 -4]]
Mean First Passage Time from state 1 to state 4: 0.75
[0.75  0.625 0.75 ]
